### ISSUE TITLE
[Bug] Release 1.33.2 is published to ansible galaxy as version 2.0.0 and when used gives the following error:   couldn't resolve module/action 't_systems_mms.icinga_director.icinga_host_info'

### ISSUE THREAD

**Issue by gjdoornink** [telekom-mms/ansible-collection-icinga-director#217]
**Issue:**

Release 1.33.2 is published to ansible galaxy as version 2.0.0, installed as version 2.0.0 and when used results in the following error:   couldn't resolve module/action 't_systems_mms.icinga_director.icinga_host_info'

The website does show version 1.33.2, but the api reports version 2.0.0 as can been seen by visiting this url: https://galaxy.ansible.com/api/v2/collections/t_systems_mms/icinga_director/versions/

**Reproduction:**

Install collection with:
ansible-galaxy collection install t_systems_mms.icinga_director

Or upgrade collection with:
ansible-galaxy collection install t_systems_mms.icinga_director --force

**Work around:**

Uninstall (remove) collection and reinstall the previous release with:
ansible-galaxy collection install t_systems_mms.icinga_director:1.33.1

**Comment by rndmh3ro** [comment]
> Release 1.33.2 is published to ansible galaxy as version 2.0.0, installed as version 2.0.0 and when used results in the following error: couldn't resolve module/action 't_systems_mms.icinga_director.icinga_host_info'

That's not what was intended.

t_systems_mms.icinga_director is published as version 2.0.0 (https://galaxy.ansible.com/api/v2/collections/t_systems_mms/icinga_director/versions/).

telekom_mms.icinga_director is published as 1.33.2 (https://galaxy.ansible.com/api/v2/collections/telekom_mms/icinga_director/versions/).

Aside: We discuss this also here: https://github.com/ansible-community/ansible-build-data/pull/261

**Comment by gjdoornink** [comment]
Thank you,

I switched to the new collection telekom_mms.icinga_director, which works just fine.
