### ISSUE TITLE
[Bug] ansible_icinga: option icinga_notifications.time_period has invalid type 'strod'

### ISSUE THREAD

**Issue by felixfontein** [telekom-mms/ansible-collection-icinga-director#259]
### Description

It should probably be 'str', not 'strod'.

### Reproduction steps

-

### Current Behavior

-

### Expected Behavior

-

### Additional information

You might want to add a docs linting step to CI: `antsibull-docs lint-collection-docs . --skip-rstcheck --plugin-docs` reports this.

(You can also see it here: https://docs.ansible.com/ansible/devel/collections/telekom_mms/icinga_director/ansible_icinga_role.html - but having that reported in CI is probably more useful :) )

**Comment by rndmh3ro** [comment]
thanks felix, fixed by #260

**Comment by rndmh3ro** [comment]
Let's add `antsibull-docs lint-collection-docs . --skip-rstcheck --plugin-docs` to the tests.

**Comment by felixfontein** [comment]
If you need an inspriation: https://github.com/ansible-collections/collection_template/blob/main/.github/workflows/extra-docs-linting.yml ;)
